name: Publish OSM Data
on:
  schedule:
    - cron: '00 7 * * *' # run every day at 07:00 UTC

jobs:
  publish_osm:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8 ]
        poetry-version: [ 1.1.6 ]
        os: [ ubuntu-18.04 ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Publish OSM Data
        run: poetry run python publish/publish.py -u ${{ secrets.BACKEND_USERNAME }} -p ${{ secrets.BACKEND_PASSWORD }} -b ${{ secrets.BACKEND_URL }} -f '../data/'

